"""The bundled team index: teams.parquet and aliases.parquet, generated by tools/build_index.py."""

from __future__ import annotations

import functools
from collections.abc import Callable
from importlib import resources
from pathlib import Path

import polars as pl

TEAM_SCHEMA: dict[str, pl.DataType] = {
    "league": pl.String(),
    "team_id": pl.String(),
    "abbr": pl.String(),
    "name": pl.String(),
    "short_name": pl.String(),
    "location": pl.String(),
    "program": pl.String(),
    "conference_id": pl.String(),
    "conference": pl.String(),
    "color_primary": pl.String(),
    "color_secondary": pl.String(),
    "color_source": pl.String(),
}
ALIAS_SCHEMA: dict[str, pl.DataType] = {
    "league": pl.String(),
    "id_system": pl.String(),
    "value": pl.String(),
    "team_id": pl.String(),
    "valid_from": pl.Int32(),
    "valid_to": pl.Int32(),
}

_RELOAD_HOOKS: list[Callable[[], None]] = []


def data_dir() -> Path:
    """Where the generated index lives inside the installed package."""
    return Path(str(resources.files("sdvplot") / "data"))


@functools.cache
def _read(name: str, directory: str) -> pl.DataFrame:
    return pl.read_parquet(Path(directory) / f"{name}.parquet")


@functools.cache
def _leagues(directory: str) -> frozenset[str]:
    return frozenset(_read("teams", directory)["league"].unique().to_list())


def check_league(league: str) -> None:
    """The one unknown-league error every public function raises."""
    known = _leagues(str(data_dir()))
    if league not in known:
        raise ValueError(f"unknown league {league!r}; known leagues: {sorted(known)}")


def on_reload(fn: Callable[[], None]) -> None:
    """Register a cache that must be dropped when the index is reloaded (the resolver's lookup tables)."""
    _RELOAD_HOOKS.append(fn)


def reload_index() -> None:
    """Forget the loaded index and everything derived from it."""
    _read.cache_clear()
    _leagues.cache_clear()
    for fn in _RELOAD_HOOKS:
        fn()


def team_table() -> pl.DataFrame:
    return _read("teams", str(data_dir()))


def alias_table() -> pl.DataFrame:
    return _read("aliases", str(data_dir()))


def index_version() -> str:
    path = data_dir() / "INDEX_VERSION"
    return path.read_text().strip() if path.exists() else "unknown"


def teams(league: str | None = None) -> pl.DataFrame:
    """The bundled team index: one row per (league, team_id), with names, abbreviation, conference and colors."""
    t = team_table()
    if league is None:
        return t
    check_league(league)
    return t.filter(pl.col("league") == league)
