import * as fs from 'fs';
import * as path from 'path';
import type {PrismTheme} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// Cap which doc versions are BUILT, derived from versions.json (which Docusaurus
// maintains newest-first) so the list never needs manual editing at release time:
// the rolling `current` tree plus the latest N release snapshots. Older snapshots
// always stay under versioned_docs/ in git; this only controls what's built/served.
//
// Default 3: the rolling `current`/`main` tree plus the latest 3 release snapshots
// = 4 versions built/served. Rolling cap, so older snapshots stop building as
// versions.json grows.
const VERSIONS_TO_KEEP = 3;
const allReleasedVersions: string[] = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'versions.json'), 'utf-8'),
);
const builtVersions: string[] = [
  'current',
  ...allReleasedVersions.slice(0, VERSIONS_TO_KEEP),
];

const PLAUSIBLE_ID = 'pa-exaiJ05ZrAXBkCgOonpbc'; // Plausible site sdvplot.sportsdataverse.org ('' disables analytics)
const analytics = PLAUSIBLE_ID
  ? {
      scripts: [{src: `https://plausible.io/js/${PLAUSIBLE_ID}.js`, async: true}],
      headTags: [{tagName: 'script', attributes: {}, innerHTML:
        'window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};plausible.init()'}],
    }
  : {scripts: [], headTags: []};

// Preload the two self-hosted faces above the fold: Inter (body) and Barlow Condensed 700 (the page
// title). The hrefs must equal the @font-face urls in src/css/sdv-theme.css or the browser fetches twice.
const fontPreloads = ['inter-latin-wght-normal', 'barlow-condensed-latin-700-normal'].map((name) => ({
  tagName: 'link',
  attributes: {rel: 'preload', href: `/fonts/${name}.woff2`, as: 'font', type: 'font/woff2', crossorigin: 'anonymous'},
}));

// Code-block themes on the family surfaces (white / #111b2e). Every token color is a sportsdataverse.org
// token and clears 4.5:1 on its background; builtins, variables and properties stay the plain text color.
const sdvPrismLight: PrismTheme = {
  plain: {color: '#0e1626', backgroundColor: '#ffffff'},
  styles: [
    {types: ['comment', 'prolog', 'doctype', 'cdata'], style: {color: '#4d5b74', fontStyle: 'italic'}},
    {types: ['punctuation', 'operator'], style: {color: '#4d5b74'}},
    {types: ['keyword', 'tag', 'selector', 'atrule', 'important'], style: {color: '#02507f'}},
    {types: ['string', 'char', 'attr-value', 'regex', 'inserted', 'triple-quoted-string', 'url'], style: {color: '#047857'}},
    {types: ['number', 'boolean', 'constant', 'symbol', 'deleted'], style: {color: '#be123c'}},
    {types: ['function', 'class-name', 'decorator', 'annotation'], style: {color: '#4a3aa7'}},
  ],
};

const sdvPrismDark: PrismTheme = {
  plain: {color: '#e9eef6', backgroundColor: '#111b2e'},
  styles: [
    {types: ['comment', 'prolog', 'doctype', 'cdata'], style: {color: '#93a1b8', fontStyle: 'italic'}},
    {types: ['punctuation', 'operator'], style: {color: '#93a1b8'}},
    {types: ['keyword', 'tag', 'selector', 'atrule', 'important'], style: {color: '#4fb6e8'}},
    {types: ['string', 'char', 'attr-value', 'regex', 'inserted', 'triple-quoted-string', 'url'], style: {color: '#10b981'}},
    {types: ['number', 'boolean', 'constant', 'symbol', 'deleted'], style: {color: '#f0537a'}},
    {types: ['function', 'class-name', 'decorator', 'annotation'], style: {color: '#9085e9'}},
  ],
};

const config: Config = {
  // Rspack/SWC build pipeline (@docusaurus/faster).
  future: {
    v4: true,
    faster: true,
  },
  title: 'sdvplot',
  tagline: "Team logos, wordmarks, headshots and colors for Python plots and tables.",
  // The site is served from the CNAME host, so canonical, og:url and og:image
  // all point at the domain links actually use.
  url: 'https://sdvplot.sportsdataverse.org',
  baseUrl: '/',
  // docs/docs/reference/ is generated by tools/gen_docs.py and docs/docs/tutorials/
  // by tools/render_notebooks.py; intro, concepts/ and adapters/ are hand-written.
  // 'throw' fails the build on any broken link: fix a generated page in its
  // generator, never by hand.
  onBrokenLinks: 'throw',
  favicon: 'img/favicon.ico',
  organizationName: 'SportsDataverse',
  projectName: 'Sportsdataverse',
  // Docusaurus 3 requires i18n declared explicitly.
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  // Detect MDX vs CommonMark per-file: `.md` pages (the generated reference
  // and tutorials) stay on CommonMark so bare braces in signatures don't trip
  // MDX; `.mdx` files keep the full MDX feature set.
  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },
  // Plausible script plus its init stub (queues calls until the async script
  // loads); nothing is emitted while PLAUSIBLE_ID is empty. Then the font preloads.
  scripts: analytics.scripts,
  headTags: [...analytics.headTags, ...fontPreloads],
  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // Generated pages (reference/, tutorials/) have no edit link: fix them in
          // their generator, never by hand.
          editUrl: ({docPath}) =>
            /^(reference|tutorials)\//.test(docPath)
              ? undefined
              : `https://github.com/sportsdataverse/sdvplot/edit/main/docs/docs/${docPath}`,
          // Versioning policy: the unversioned tree under docs/docs/ (the generated
          // reference + tutorials and the hand-written pages) is the live
          // DEFAULT served at the root URL (`lastVersion: 'current'`), so every
          // push to main republishes it (docs-deploy.yml builds and publishes to
          // gh-pages, which Vercel serves) and it can never drift from the code
          // (`tools/gen_docs.py --check` keeps the reference pages == the docstrings).
          // It is labelled `main` — a rolling, collision-proof label — so that the
          // per-release snapshots cut at release time (`yarn version:docs x.y.z`,
          // which freezes a copy under versioned_docs/version-x.y.z) get the exact
          // release numbers without ever clashing with `current`'s label.
          lastVersion: 'current',
          // `current` + the latest 3 release snapshots (see builtVersions above).
          // Auto-derived from versions.json so new releases never re-break the
          // build by accumulating versioned-docs copies.
          onlyIncludeVersions: builtVersions,
          versions: {
            current: {
              label: 'main',
              path: '',
              banner: 'none',
            },
          },
        },
        // No blog: release notes live on the CHANGELOG page (navbar "News").
        blog: false,
        theme: {
          // The shared family theme first, then what only this site needs.
          customCss: ['./src/css/sdv-theme.css', './src/css/custom.css'],
        },
      } satisfies Preset.Options,
    ],
  ],
  // Offline/local full-text search (no Algolia account, no external crawler —
  // the index is built into the static output at build time). With versioning
  // enabled the plugin indexes only the preferred (`current`/`main`) version,
  // so the index doesn't grow with each release snapshot.
  themes: [
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        indexBlog: false,
      },
    ],
  ],
  themeConfig: {
    docs: {
      sidebar: {
        hideable: true,
      },
    },
    colorMode: {
      defaultMode: 'light',
      disableSwitch: false,
      respectPrefersColorScheme: true,
    },
    image: 'img/Sportsdataverse_gh.png',
    // Social metadata Docusaurus does not emit on its own. og:image alone renders
    // a bare card on several platforms; the type, site name, image dimensions and
    // Twitter attribution are what make the preview complete.
    metadata: [
      { property: 'og:type', content: 'website' },
      { property: 'og:site_name', content: 'sdvplot | SportsDataverse' },
      { property: 'og:image:width', content: '1080' },
      { property: 'og:image:height', content: '540' },
      { property: 'og:image:alt', content: 'SportsDataverse' },
      { name: 'twitter:site', content: '@sportsdataverse' },
      { name: 'twitter:creator', content: '@saiemgilani' },
      { name: 'twitter:image:alt', content: 'SportsDataverse' },
    ],
    navbar: {
      hideOnScroll: true,
      // Navy in both color modes, like sportsdataverse.org; sdv-theme.css sets the colors.
      style: 'dark',
      title: 'sdvplot',
      logo: {
        alt: 'sdvplot logo',
        src: 'img/logo.png',
      },
      items: [
        {
          type: 'doc',
          docId: 'intro',
          position: 'left',
          label: 'Docs',
        },
        {
          label: 'News',
          to: 'CHANGELOG',
          position: 'left',
        },
        {
          type: 'docsVersionDropdown',
          position: 'right',
          dropdownActiveClassDisabled: true,
        },
        // SportsDataverse package directory. Sourced from
        //   https://sportsdataverse.org/packages
        //   https://github.com/sportsdataverse/.github/blob/main/profile/README.md
        // Keep this dropdown in sync with those two pages.
        // The `sdv-packages-dropdown` className triggers the multi-column
        // mega-menu layout in sdv-theme.css; without it the 30+ package list
        // overflows the viewport vertically on a typical laptop.
        {
          label: 'SDV',
          position: 'left',
          className: 'sdv-packages-dropdown',
          items: [
            {
              href: 'https://sportsdataverse.org',
              label: 'SportsDataverse',
              target: '_self',
              className: 'sdv-section-header',
            },
            // -- Python --
            {
              label: 'Python Packages',
              href: 'https://py.sportsdataverse.org/',
              target: '_self',
              className: 'sdv-section-header',
            },
            {
              label: 'sportsdataverse-py',
              href: 'https://py.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'sdvplot',
              href: 'https://sdvplot.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'sportypy',
              href: 'https://sportypy.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'collegebaseball',
              href: 'https://collegebaseball.readthedocs.io/en/latest/index.html',
              target: '_self',
            },
            {
              label: 'nwslpy',
              href: 'https://github.com/nwslR/nwslpy',
              target: '_self',
            },
            // -- R --
            {
              label: 'R Packages',
              href: 'https://r.sportsdataverse.org/',
              className: 'sdv-section-header',
            },
            {
              label: 'sportsdataverse-R',
              href: 'https://r.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'sdvplotR',
              href: 'https://sdvplotR.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'cfbfastR',
              href: 'https://cfbfastR.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'hoopR',
              href: 'https://hoopR.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'wehoop',
              href: 'https://wehoop.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'fastRhockey',
              href: 'https://fastRhockey.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'baseballr',
              href: 'https://BillPetti.github.io/baseballr/',
              target: '_self',
            },
            {
              label: 'sportyR',
              href: 'https://sportyR.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'ggshakeR',
              href: 'https://abhiamishra.github.io/ggshakeR/',
              target: '_self',
            },
            {
              label: 'soccerAnimate',
              href: 'https://github.com/Dato-Futbol/soccerAnimate',
              target: '_self',
            },
            {
              label: 'oddsapiR',
              href: 'https://oddsapiR.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'mlbplotR',
              href: 'https://camdenk.github.io/mlbplotR/',
              target: '_self',
            },
            {
              label: 'cfbplotR',
              href: 'https://cfbplotR.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'cfb4th',
              href: 'https://cfb4th.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'softballR',
              href: 'https://github.com/sportsdataverse/softballR/',
              target: '_self',
            },
            {
              label: 'nwslR',
              href: 'https://github.com/nwslR/nwslR/',
              target: '_self',
            },
            {
              label: 'usfootballR',
              href: 'https://usfootballR.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'recruitR',
              href: 'https://recruitR.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'puntr',
              href: 'https://puntalytics.github.io/puntr/',
              target: '_self',
            },
            {
              label: 'chessR',
              href: 'https://jaseziv.github.io/chessR/',
              target: '_self',
            },
            // -- Node.js --
            {
              label: 'Node.js Packages',
              href: 'https://js.sportsdataverse.org/',
              className: 'sdv-section-header',
            },
            {
              label: 'sportsdataverse.js',
              href: 'https://js.sportsdataverse.org/',
              target: '_self',
            },
            {
              label: 'nfl-nerd',
              href: 'https://github.com/nntrn/nfl-nerd/',
              target: '_self',
            },
          ],
        },
        {
          label: 'Data status',
          href: 'https://sportsdataverse.org/status',
          position: 'right',
        },
        {
          label: 'GitHub',
          href: 'https://github.com/sportsdataverse/sdvplot',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Docs',
              to: '/docs/intro',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'Twitter (Author)',
              href: 'https://twitter.com/saiemgilani',
            },
            {
              label: 'Twitter (SportsDataverse)',
              href: 'https://twitter.com/sportsdataverse',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/sportsdataverse/sdvplot',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} <strong>sdvplot</strong>, developed by <a href='https://twitter.com/saiemgilani'>Saiem Gilani</a>, part of the <a href='https://sportsdataverse.org'>SportsDataverse</a>.`,
    },
    prism: {
      // The family themes defined above: one surface per mode, every token at 4.5:1 or better.
      theme: sdvPrismLight,
      darkTheme: sdvPrismDark,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
