import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// Written by tools/gen_docs.py from its SECTIONS groups (gated by gen_docs.py --check): the overview, one category
// per group, the errors page. The doc ids are the file paths, so grouping changes no page URL.
import referenceItems from './src/data/reference_sidebar.json';

// Hand-written pages first; the API reference (tools/gen_docs.py) and the executed-notebook tutorials
// (tools/render_notebooks.py) are generated, so new functions and notebooks need no sidebar edit.
const sidebars: SidebarsConfig = {
  docs: [
    {type: 'doc', id: 'intro', label: 'Getting started'},
    {
      type: 'category',
      label: 'Concepts',
      items: ['concepts/identity', 'concepts/seasons-and-eras', 'concepts/logos', 'concepts/colors', 'concepts/cache'],
    },
    {
      type: 'category',
      label: 'API reference',
      items: referenceItems as SidebarsConfig[string],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {type: 'generated-index', title: 'Tutorials',
        description: 'Executed example notebooks rendered as pages; source notebooks live in examples/notebooks/.'},
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {type: 'category', label: 'For adapter authors', items: ['adapters/contract']},
  ],
};

export default sidebars;
