import * as fs from 'fs';
import * as path from 'path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// Written by tools/gen_docs.py from its SECTIONS groups (gated by gen_docs.py --check): the overview, one category
// per group, the errors page. The doc ids are the file paths, so grouping changes no page URL.
import referenceItems from './src/data/reference_sidebar.json';

type Items = SidebarsConfig[string];

// The notebook sections (tools/render_notebooks.py) and the automation guide: each is a docs/ dir whose
// _category_.json (label, position, index page) the renderer writes once the section has a notebook; automation/
// has a hand-written one. A section shows once its dir holds that file and a page (Docusaurus rejects an empty
// category), in position order.
const sectionDirs = ['tutorials/leagues', 'cookbooks', 'recipes', 'leaderboards', 'automation'];
const sections = sectionDirs
  .map((dirName) => ({dirName, dir: path.join(__dirname, 'docs', dirName)}))
  .filter(({dir}) => fs.existsSync(path.join(dir, '_category_.json')))
  .filter(({dir}) => fs.readdirSync(dir).some((name) => /\.mdx?$/.test(name)))
  .map(({dirName, dir}) => ({dirName, ...JSON.parse(fs.readFileSync(path.join(dir, '_category_.json'), 'utf-8'))}))
  .sort((a, b) => a.position - b.position)
  .map(({dirName, label, link}) => ({
    type: 'category',
    label,
    ...(link ? {link} : {}),
    items: [{type: 'autogenerated', dirName}],
  })) as Items;

// Hand-written pages, the API reference (tools/gen_docs.py), then the notebook pages (generated, so a new notebook
// needs no sidebar edit) and the gallery.
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting started',
      link: {type: 'doc', id: 'intro'},
      // the top-level tutorials (docusaurus.config.ts drops tutorials/leagues/ from this list)
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: ['concepts/identity', 'concepts/seasons-and-eras', 'concepts/logos', 'concepts/colors', 'concepts/cache'],
    },
    {
      type: 'category',
      label: 'API reference',
      items: referenceItems as Items,
    },
    ...sections,
    {type: 'doc', id: 'gallery', label: 'Gallery'},
    {type: 'category', label: 'For adapter authors', items: ['adapters/contract', 'adapters/add-an-adapter']},
  ],
};

export default sidebars;
